LanType = "EN"
Checkbox_Enable = "Enable {0}"
Checkbox_AutoEnable = "Auto Enable"
Checkbox_Multi = "Multi"
DrawEnum_Language = "Language:"
EzTabBar_Retainers = "Retainers"
EzTabBar_MultiMode = "Multi Mode"
EzTabBar_Statistics = "Statistics"
EzTabBar_Settings = "Settings"
EzTabBar_Beta = "Beta"
EzTabBar_About = "About"
EzTabBar_Log = "Log"
EzTabBar_Debug = "Debug"
Retainers = "Retainers"
Text_DataNotReady = "Data Not Ready"
Text_InventorySlots = "Inventory slots"
Text_Ventures = "Ventures:"
HelpMarker_Ventures = "The plugin will automatically disable itself at < 2 Ventures or inventory slots available."
TableSetupColumn_Name = "Name"
TableSetupColumn_Venture = "Venture"
TableSetupColumn_Interaction = "Interaction"
Checkbox_RetainerName = "Retainer {0}"
ImGuiLineCentered_Timeouts = "AYSButtonClear Interaction Timeouts"
SmallButton_Timeouts = "Clear Interaction Timeouts"
TextWrapped_MultiMode = "Multi Mode requires Auto-afk option to be turned off"
TextWrapped_Please = "Please use this feature within the sane limits. Keeping it on for abnormally large amount of time may attract unwanted attention."
CollapsingHeader_SetupGuide = "Setup Guide"
TextWrapped_1 = "1. Log into each of your characters, assign necessary ventures to your retainers and enable retainers that you want to resend on each character."
TextWrapped_2 = "2. For each character, configure character index. Character index is position of your character on a screen where you select characters. If you only have one character per world, it's usually just 1."
TextWrapped_3 = "3. Ensure that your characters are in their home worlds and close to retainer bells, preferably in not crowded areas. No housing retainer bells. The suggested place is the inn."
TextWrapped_4 = "4. Characters that ran out of ventures or inventory space will be automatically excluded from rotation. You will need to reenable them once you clean up inventory and restock ventures."
TextWrapped_5 = "5. You may set up one character to be preferred. When no retainers have upcoming ventures in next 15 minutes, you will be relogged back on that character."
CollapsingHeader_Configuration = "Configuration"
Checkbox_MultiWaitForAll = "Wait for all retainers to be done before logging into character"
DragInt_AdvanceTimer = "Relog in advance, seconds"
Checkbox_Synchronize = "Synchronize retainers (one time)"
HelpMarker_Synchronize = "If this setting is on, plugin will wait until all enabled retainers have done their ventures. After that this setting will be disabled automatically and all characters will be processed."
Notify_Error_Setcharacterindexfirst = "Set character index first"
Button_Relog = "Relog"
Notify_Warning_Preferredcharacterhasbeenreset = "Preferred character has been reset"
Notify_Success_Relogging = "Relogging..."
CollapsingHeader_Characterindex = "Character {0}"
TextV_Characterindex = "Character index:"
Setting_Settings = "Settings"
Setting_AutoEnableDisable = "Semi-automatic Mode"
Setting_AutoEnableDisable_HelpMarker = "Automatically enables the plugin on Summoning Bell interaction. You can hold down the SHIFT key to disable this behavior."
Setting_TurboMode = "Turbo Mode"
Setting_TurboMode_HelpMarker = "Rapidly collect rewards and despatch retainers on new ventures. Only works in semi-automatic mode/with manual player interaction."
Setting_UnsyncCompensation = "Time Desynchronization Compensation"
Setting_UnsyncCompensation_HelpMarker = "Additional amount of seconds that will be subtracted from venture ending time to help mitigate possible issues of time desynchronization between the game and your PC. "
Setting_Speed = "Interaction Speed (%)"
Setting_Speed_HelpMarker = "The higher this value is the faster plugin will operate retainers. When dealing with low FPS or high latency you may want to decrease this value. If you want the plugin to operate faster you may increase it."
Setting_AnonymiseRetainers = "Anonymise Retainers"
Setting_AnonymiseRetainers_HelpMarker = "Retainer names will be redacted from general UI elements. They will not be hidden in debug menus and plugin logs however. While this option is on, character and retainer numbers are not guaranteed to be equal in different sections of a plugin (for example, retainer 1 in retainers view is not guaranteed to be the same retainer as in statistics view)."
Setting_Operation = "Operation"
